title: SceneView
description: 3D and AR View for Android, iOS and React Native (Android and iOS) working with ARCore/ARKit and Google Filament

header_pages:
  - features.md
  - apps.md
  - sponsoring.md

show_excerpts: false

minima:
  skin: dark
  social_links:
    twitter: thomas_gorisse
    github: sceneview
    linkedin: thomas-gorisse
    youtube_channel: UCY6PxZTBNb_5zeLicxDCjxw
    youtube_channel_name: SceneView

markdown: GFM

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
