url: "https://sceneview.github.io"
title: SceneView
description: 3D and AR View for Android, iOS and React Native (Android and iOS) working with ARCore/ARKit and Google Filament

header_pages:
  - features.md
  - apps.md
  - api.md
  - contribute.md
  - assets.md

show_excerpts: false

minima:
  skin: light
  social_links:
    - { platform: github,  user_url: "https://github.com/SceneView" }
    - { platform: twitter,  user_url: "https://twitter.com/thomas_gorisse" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/thomas-gorisse/" }
    - { platform: youtube,  user_url: "https://www.youtube.com/channel/UCY6PxZTBNb_5zeLicxDCjxw" }

markdown: GFM

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
